// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	BatchInsertDeviceData(ctx context.Context, arg []BatchInsertDeviceDataParams) error
}

var _ Querier = (*Queries)(nil)
