networks:
  viot:
    driver: bridge

volumes:
  emqx-data:
    name: emqx-data
  emqx-log:
    name: emqx-log
  mailpit-data:
    name: mailpit-data

services:
  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/templates/default.nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - viot-api
    networks:
      viot:
        aliases:
          - nginx

  emqx:
    image: emqx:5.8.0
    container_name: emqx
    restart: unless-stopped
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-log:/opt/emqx/log
      - ./docker/emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf
      - ./docker/emqx/etc/acl.conf:/opt/emqx/etc/acl.conf
      - ./docker/emqx/etc/api_keys:/opt/emqx/etc/api_keys
      - ./docker/emqx/etc/cluster.hocon:/opt/emqx/data/configs/cluster.hocon
    environment:
      - EMQX_HOST=node1.viot
    networks:
      viot:
        aliases:
          - node1.viot

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/timescaledb/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      viot:
        aliases:
          - timescaledb

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      viot:
        aliases:
          - redis

  mailpit:
    image: axllent/mailpit:v1.20.0
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      viot:
        aliases:
          - mailpit

  viot-api:
    build:
      context: .
      dockerfile: ./docker/viot/viot.dockerfile
      args:
        INSTALL_DEV: true
    container_name: viot-api
    restart: unless-stopped
    environment:
      - VIOT_ENV=dev
      - VIOT_DOMAIN=viot.local
      - VIOT_API_DOMAIN=api.viot.local
      - VIOT_API_PORT=8000
      - VIOT_API_PREFIX=/v1
      - VIOT_UI_URL=http://localhost:5173
      - VIOT_ALLOW_CREDENTIALS=true
      - VIOT_ALLOW_CORS_ORIGINS=["http://localhost:5173", "http://fe.viot.local"]
      - VIOT_POSTGRES_SERVER=timescaledb
      - VIOT_POSTGRES_PORT=5432
      - VIOT_POSTGRES_USER=postgres
      - VIOT_POSTGRES_PASSWORD=postgres
      - VIOT_POSTGRES_DB=postgres
      - VIOT_REDIS_SERVER=redis
      - VIOT_REDIS_PORT=6379
      - VIOT_AUTH_JWT_SECRET=secret
      - VIOT_EMQX_API_URL=http://node1.viot:18083/api/v5
      - VIOT_EMQX_API_KEY=ABC1234
      - VIOT_EMQX_SECRET_KEY=ec7122ff-c6c6-4b6b-91eb-5593d7b09437
      - VIOT_EMQX_MQTT_WHITELIST_FILE_PATH=./mqtt_whitelist
      - VIOT_CELERY_REDIS_SERVER=redis
      - VIOT_CELERY_REDIS_PORT=6379
      - VIOT_CELERY_BROKER_REDIS_DATABASE=0
      - VIOT_CELERY_BACKEND_REDIS_DATABASE=1

      # https://github.com/testcontainers/testcontainers-python/issues/475#issuecomment-2334343767
      - TESTCONTAINERS_RYUK_DISABLED=true
    user: root # Required for pytest with testcontainers
    volumes:
      - ./viot:/viot
      # Required for pytest with testcontainers
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - emqx
      - redis
      - timescaledb
    networks:
      viot:
        aliases:
          - viot

  viot-celery:
    build:
      context: .
      dockerfile: ./docker/viot/celery.dockerfile
    container_name: viot-celery
    restart: unless-stopped
    environment:
      - VIOT_CELERY_REDIS_SERVER=redis
      - VIOT_CELERY_REDIS_PORT=6379
      - VIOT_CELERY_BROKER_REDIS_DATABASE=0
      - VIOT_CELERY_BACKEND_REDIS_DATABASE=1
      - VIOT_EMAIL_SMTP_HOST=mailpit
      - VIOT_EMAIL_SMTP_PORT=1025
      - VIOT_EMAIL_SMTP_USER=admin
      - VIOT_EMAIL_SMTP_PASSWORD=admin
      - VIOT_EMAIL_SMTP_TLS=false
      - VIOT_EMAIL_SMTP_SSL=false
    depends_on:
      - viot-api
      - redis
      - mailpit
    networks:
      viot:
        aliases:
          - viot-celery
