// Code generated by mockery v2.46.3. DO NOT EDIT.

package mockdb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/vuxmai/viot/viot-background/db/repository"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// BatchInsertDeviceData provides a mock function with given fields: ctx, arg
func (_m *Store) BatchInsertDeviceData(ctx context.Context, arg []repository.BatchInsertDeviceDataParam) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for BatchInsertDeviceData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.BatchInsertDeviceDataParam) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BatchUpsertDeviceAttribute provides a mock function with given fields: ctx, arg
func (_m *Store) BatchUpsertDeviceAttribute(ctx context.Context, arg []repository.BatchUpsertDeviceAttributeParam) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpsertDeviceAttribute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []repository.BatchUpsertDeviceAttributeParam) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
