// Code generated by sqlc.
// versions:
//   sqlc v1.27.0

package repository

import (
	"context"
)

type Querier interface {
	BatchInsertDeviceData(ctx context.Context, arg []BatchInsertDeviceDataParam) error
	BatchUpsertDeviceAttribute(ctx context.Context, arg []BatchUpsertDeviceAttributeParam) error
}

var _ Querier = (*Queries)(nil)
