[program:celery_worker]
directory=/code
command=/usr/local/bin/celery -A app.modules.celery_task.celery worker --loglevel=INFO
user=viot
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/celery/celery_worker.log

[program:celery_beat]
directory=/code
command=/usr/local/bin/celery -A app.modules.celery_task.celery beat --loglevel=INFO
user=viot
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/celery/celery_beat.log

[program:celery_flower]
directory=/code
command=/usr/local/bin/celery -A app.modules.celery_task.celery flower --port=8555 --basic-auth=admin:123456
user=viot
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/var/log/celery/celery_flower.log
