BCRYPT_SALT_ROUNDS = 12

REDIS_REFRESH_TOKEN_PREFIX = "rf"
REDIS_INVALID_ACCESS_TOKEN_PREFIX = "ia"
REDIS_RESET_PASSWORD_PREFIX = "rp"


class AuthErrorCode:
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    INVALID_TOKEN = "INVALID_TOKEN"
    NOT_VERIFIED = "NOT_VERIFIED"
    ACCOUNT_DISABLED = "ACCOUNT_DISABLED"
