"""device attribute add unique constraint

Revision ID: fe4aab5e136c
Revises: 360da95a3d9e
Create Date: 2024-10-29 07:38:19.126733

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe4aab5e136c"
down_revision: str | None = "360da95a3d9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "device_attribute_device_id_key_scope_unique",
        "device_attribute",
        ["device_id", "key", "scope"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "device_attribute_device_id_key_scope_unique", "device_attribute", type_="unique"
    )
    # ### end Alembic commands ###
