"""user team role

Revision ID: 26c05dc31076
Revises:
Create Date: 2024-08-01 08:40:32.770262

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.database.types import TSVectorType

# revision identifiers, used by Alembic.
revision: str = "26c05dc31076"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("scope", sa.TEXT(), nullable=False),
        sa.Column("action", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "action"),
    )
    op.create_index(op.f("ix_permission_id"), "permission", ["id"], unique=True)
    op.create_table(
        "team",
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_team_id"), "team", ["id"], unique=True)
    op.create_table(
        "viot_user",
        sa.Column("first_name", sa.TEXT(), nullable=False),
        sa.Column("last_name", sa.TEXT(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=False),
        sa.Column(
            "email_vector",
            TSVectorType(),
            sa.Computed("to_tsvector('pg_catalog.simple', \"email\")", persisted=True),
            nullable=False,
        ),
        sa.Column("password", sa.LargeBinary(), nullable=False),
        sa.Column("role", sa.TEXT(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_viot_user_email"), "viot_user", ["email"], unique=True)
    op.create_index(op.f("ix_viot_user_id"), "viot_user", ["id"], unique=True)
    op.create_index(
        "viot_user_email_vector_idx",
        "viot_user",
        ["email_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "role",
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "team_id"),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=True)
    op.create_table(
        "role_permission",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "viot_user_team",
        sa.Column("viot_user_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["viot_user_id"],
            ["viot_user.id"],
        ),
        sa.PrimaryKeyConstraint("viot_user_id", "team_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("viot_user_team")
    op.drop_table("role_permission")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    op.drop_index("viot_user_email_vector_idx", table_name="viot_user", postgresql_using="gin")
    op.drop_index(op.f("ix_viot_user_id"), table_name="viot_user")
    op.drop_index(op.f("ix_viot_user_email"), table_name="viot_user")
    op.drop_table("viot_user")
    op.drop_index(op.f("ix_team_id"), table_name="team")
    op.drop_table("team")
    op.drop_index(op.f("ix_permission_id"), table_name="permission")
    op.drop_table("permission")
    # ### end Alembic commands ###
